Test if theme and author URI have a valid responses
WordPress/theme-review-action pull request #52
Opened 2021-07-12 09:25 UTC by carolinan

Use `pageStatusTest` to test theme and author URI fetched from _siteInfo.theme_urls_.

Tested by changing the theme and author URI of the test theme.

Resulting error report when the URL does not return 202:
```
Expected to received a 200 status for https://wordpress.org/gfdgfd. Received 404.
See: https://github.com/WordPress/theme-review-action/blob/trunk/docs/ui-errors.md#page-should-return-200-status
```

2021-07-12 09:28 UTC, carolinan commented
As I submitted this, I realized I never tested what happens if the style.css file header is empty:
```
Theme URI:
Author URI:
```
So I put this as draft while I continue.

2021-07-12 10:04 UTC, carolinan commented
`if ( theme_urls !== null ) {` Feels a bit primitive but it means that if the links have not been added, the test does not run,
if there is one link, the test still runs and passes and fails correctly.

2021-07-21 01:31 UTC, StevenDufresne requested changes
There isn't a great way to conditionally run tests. There are some tactics that we can use by adding `.skip` but it's more designed for excluding broken and irrelevant tests. I've run into some problems with it combining it with `describe` & `.each`. 

I think it's clear enough and represents the intention well enough for now. If it starts to creep, we can revisit.

2021-07-21 01:31 UTC, StevenDufresne commented on actions/ui-check/tests/e2e/specs/page/index.test.js
> +if ( theme_urls !== null ) {
The theme_urls will never be null:

https://github.com/WordPress/theme-review-action/blob/e18c14acaa4c570015b44a1050ea9b3ff6f9da14/helpers/theme-test-helper-plugin.php#L48

```suggestion
if ( theme_urls[0]) {
```

2021-07-21 01:31 UTC, StevenDufresne commented on actions/ui-check/tests/e2e/specs/page/index.test.js
> +	describe.each( theme_urls )('Test URL %s%s', ( url ) => {
```suggestion
	describe.each( theme_urls )('Test URL %s', ( url ) => {
```

2021-07-22 22:25 UTC, merged